### ISSUE TITLE
[RESOLVED]Error with from astropy.convolution import Gaussian1DKernel

### ISSUE THREAD

**Issue by jglorian** [pyinstaller/pyinstaller-hooks-contrib#129]
When I try to run the program packaged with pyinstaller with the code below, 
I have  

> Traceback (most recent call last):
>   File "astropy/convolution/convolve.py", line 24, in <module>
>   File "numpy/ctypeslib.py", line 127, in load_library
> ModuleNotFoundError: No module named 'numpy.distutils'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent ## Description of the issuecall last):
>   File "main.py", line 6, in <module>
>     from astropy.convolution import Gaussian1DKernel
>   File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
>   File "astropy/convolution/__init__.py", line 8, in <module>
>   File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
>   File "astropy/convolution/convolve.py", line 26, in <module>
> ImportError: Convolution C extension is missing. Try re-building astropy.
> [11847] Failed to execute script main

I have done this with python3.7, under Ubuntu and with the last version of all the libraries.
I also try with different versions of python and libraries but I have still  the same problem
Can you help me ?

```
import matplotlib.pyplot as plt
from astropy.convolution import Gaussian1DKernel

if __name__ == '__main__':
    gauss_1D_kernel = Gaussian1DKernel(10)
    plt.plot(gauss_1D_kernel, drawstyle='steps')
    plt.xlabel('x [pixels]')
    plt.ylabel('value')
    plt.show()
```

**Comment by rokm** [comment]
You'll need to add `numpy.distutils` (and several submodules from it) to `hiddenimports`. On PyInstaller 4.3, the easiest way to do so is adding `--collect-submodules numpy.distutils` to your pyinstaller command line.

**Comment by rokm** [comment]
Hmm, this actually looks like a bug in our `numpy` hook - it explicitly [excludes `numpy.distutils`](https://github.com/pyinstaller/pyinstaller/blob/e35a0a85e602b2ba0a4d7bb60043633dabe8b67c/PyInstaller/hooks/hook-numpy.py#L58) (which is why as an above work-around, its collection needs to be forced manually).

**Comment by bwoodsend** [comment]
Yes. I deliberately excluded that because it was said in https://github.com/numpy/numpy/issues/17184#issuecomment-683303397 that is was unlikely to be useful (and tbh I can't understand why astropy would need it).

**Comment by bwoodsend** [comment]
I'd rather that the odd library which does somehow depend on `numpy.distutils` should `--hiddenimport` it in rather that change to numpy hook to include it by default.

**Comment by rokm** [comment]
It's not `astropy`'s fault, though  - at least not directly. It's [`numpy.ctypeslib.load_library` (that `astropy` uses to load its private extensions) that imports `numpy.distutils`](https://github.com/numpy/numpy/blob/75f852edf94a7293e7982ad516bee314d7187c2d/numpy/ctypeslib.py#L128). But I suppose using `numpy`'s convenience function instead of using `ctypes` directly might fall under the same argument...

**Comment by bwoodsend** [comment]
Grrr. I really like NumPy but I seriously wish it would separate its public API from its gut from its test suite from its build system...

I guess that we'll have to remove that exclusion then.

**Comment by jglorian** [comment]
Solved with 

`pyinstaller --onefile --collect-submodules numpy.distutils main.py `

**Comment by bwoodsend** [comment]
I'm going to keep this open as it needs to be addressed in the numpy hook.
