### ISSUE TITLE
"FileNotFoundError: [Errno 2]" when creating exe with langdetect

### ISSUE THREAD

**Issue by yucongo** [pyinstaller/pyinstaller-hooks-contrib#285]
# applangdetect.py
    import langdetect

    print('test', langdetect.detect('this is a test'))
    # end of applangdetect.py

pyinstaller applangdetect.py

applangdetect.exe

    Traceback (most recent call last):
      File "applangdetect.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "d:\python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
     line 631, in exec_module
        exec(bytecode, module.__dict__)
      File "site-packages\langdetect\__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "d:\python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
     line 631, in exec_module
        exec(bytecode, module.__dict__)
      File "site-packages\langdetect\detector_factory.py", line 10, in <module>
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "d:\python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
     line 631, in exec_module
        exec(bytecode, module.__dict__)
      File "site-packages\langdetect\detector.py", line 9, in <module>
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "d:\python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
     line 631, in exec_module
        exec(bytecode, module.__dict__)
      File "site-packages\langdetect\utils\ngram.py", line 23, in <module>
      File "site-packages\langdetect\utils\ngram.py", line 24, in NGram
      File "site-packages\langdetect\utils\messages.py", line 22, in get_string
      File "site-packages\langdetect\utils\messages.py", line 9, in __init__
    FileNotFoundError: [Errno 2] No such file or directory: 'd:\\dl\\Dropbox\\mat-di
    r\\snippets-mat\\wxpython\\dist\\applangdetect\\langdetect\\utils\\messages.prop
    erties'
    Failed to execute script applangdetect

[Windows 7, 32 bits, Python 3.4,  PyInstaller==3.3.dev0+abfc80661, langdetect==1.0.7]

Simplest of all  "print(langdetec.detect("test")) cannot be packed by pyintaller. 

What should I do to fix this? Any hints will be appreciated.

(Also reported in https://github.com/pyinstaller/pyinstaller/issues/1842, seems not fixed)

**Comment by bwoodsend** [comment]
If your PyInstaller version is reasonably recent, you should now be able to use:
```
pyinstaller --collect-datas=langdetect your-code.py
```

**Comment by Aniskonig** [comment]
Thank you so much that's solved my problem
