### ISSUE TITLE
Support Hydra config system

### ISSUE THREAD

**Issue by Interpause** [pyinstaller/pyinstaller-hooks-contrib#424]
[Hydra](https://github.com/facebookresearch/hydra) is a composable config system and CLI parser. One use for it is as a config system for complex servers complete with logs and config tracking per run. 

**Have you gotten the library to work with pyinstaller?**

No. Using `--collect-all` I am currently stuck at:

```sh
Traceback (most recent call last):
  File "nicepipe\__main__.py", line 130, in <module>
  File "hydra\main.py", line 48, in decorated_main
  File "hydra\_internal\utils.py", line 324, in _run_hydra
  File "hydra\_internal\utils.py", line 181, in create_automatic_config_search_path
  File "hydra\_internal\utils.py", line 194, in create_config_search_path
  File "hydra\core\plugins.py", line 41, in instance
  File "hydra\core\singleton.py", line 17, in instance
  File "hydra\core\singleton.py", line 13, in __call__
  File "hydra\core\plugins.py", line 49, in __init__
  File "hydra\core\plugins.py", line 62, in _initialize
  File "hydra\core\plugins.py", line 257, in _scan_all_plugins
AssertionError
[19908] Failed to execute script '__main__' due to unhandled exception!
```

Seems to be an issue with how they scan for plugins. <https://hydra.cc/docs/advanced/plugins/develop/#plugin-discovery-process>

**Comment by bwoodsend** [comment]
How far does `--collect-submodules=hydra_plugins` get you?

**Comment by Interpause** [comment]
I'm afraid it doesn't get any further. Adding `--collect-submodules=hydra_plugins` still ends up triggering the assertion.

**Comment by rokm** [comment]
> ```shell
>   File "hydra\core\plugins.py", line 257, in _scan_all_plugins
> AssertionError
> [19908] Failed to execute script '__main__' due to unhandled exception!
> ```

That's because `--collect-all` is more often than not a problem in disguise. It results in package being collected both as byte-compiled modules (the regular PyInstaller's collection mechanism) as well as source .py files. This results in duplicated plugin entries, which hydra 1.1.2 [explicitly checks against](https://github.com/facebookresearch/hydra/blob/59e8b3b39d5d51fd3f3d1ecd9007d204042c8c07/hydra/core/plugins.py#L257). In the latest release (1.2.0) this constraint seems to have been removed or relaxed, so you could get away with a `--collect-all hydra`.

But the proper way to address this is `--collect-submodules hydra._internal.core_plugins --collect-data hydra`.

**Comment by Interpause** [comment]
Thanks!
