### ISSUE TITLE
VTK hook support request

### ISSUE THREAD

**Issue by Jaime02** [pyinstaller/pyinstaller-hooks-contrib#492]
**Which library is the hook for?**

VTK

**Have you gotten the library to work with pyinstaller?**

No, I tried hidden imports but they did not work

**Additional context**

This is my crash traceback: 
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "window.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "RobotToolWidgets.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "vtkmodules\qt\QVTKRenderWindowInteractor.py", line 74, in <module>
ImportError: Failed to load vtkRenderingCore: No module named vtkmodules.vtkCommonCore
[10144] Failed to execute script 'main' due to unhandled exception!
```

I have seen that this issue is related:
https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/327

**Comment by bwoodsend** [comment]
We don't need a second copy of #327.
