### ISSUE TITLE
Missing plugin with imread in SKIMAGE

### ISSUE THREAD

**Issue by chaoxinzheng** [pyinstaller/pyinstaller-hooks-contrib#510]
Building script with SKIMAGE as below:
```
import os
from skimage import io
import skimage
from skimage.viewer import ImageViewer
import sys
from tkinter import *
import PIL
from PIL import Image as PILImage
import PIL.ImageTk as imagetk
import tkinter.filedialog

path = tkinter.filedialog.askopenfilename()
moon = io.imread(path)
imviewer = ImageViewer(moon)
imviewer.show()
```
The above script works while in Spyder but generating the below error after building with Pyinstaller
```
Traceback (most recent call last):
  File "imread_example.py", line 13, in <module>
  File "site-packages\skimage\io\_io.py", line 61, in imread
  File "contextlib.py", line 77, in __exit__
  File "site-packages\skimage\io\util.py", line 36, in file_or_url_context
  File "site-packages\skimage\io\_io.py", line 61, in imread
  File "site-packages\skimage\io\manage_plugins.py", line 198, in call_plugin
RuntimeError: No suitable plugin registered for imread.

You may load I/O plugins with the `skimage.io.use_plugin` command.  A list of all available plugins are shown in the `skimage.io` docstring.
```
I have tried solution from this link, but not working.

https://stackoverflow.com/questions/40676027/pyinstaller-valueerror-too-many-values-to-unpack?noredirect=1&lq=1

It indicates that the library cannot be found.

**Comment by GenevieveBuckley** [comment]
Should this issue be closed now that https://github.com/pyinstaller/pyinstaller/pull/3934 is merged?

**Comment by bwoodsend** [comment]
So it can
