### ISSUE TITLE
Missing file for charset-normalizer==3.0.1

### ISSUE THREAD

**Issue by ikus060** [pyinstaller/pyinstaller-hooks-contrib#534]
## Description of the issue

Trying to froze an application is failing.
Requests is not working in PyInstaller packages because of missing file from charset_normalizer module.

### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.7.0
* Version of Python: Any
* Platform: Linux, Windows, Mac
* How you installed Python: n/a
* Did you also try this on another platform? Does it work there?
* try the latest development version, using the following command: Get the same issue.

### A minimal example program which shows the error

test.py:
```
import requests

print(requests.get('http://example.com'))
```

```
pip install requests==2.28.2 charset-normalizer==3.0.1 pyinstaller
pyinstaller test.py
dist/test/test
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minarca_client\main.py", line 15, in <module>
    from minarca_client.core import (
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "minarca_client\core\__init__.py", line 23, in <module>
    import requests
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\__init__.py", line 45, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\exceptions.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "requests\compat.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\api.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md__mypyc'
```

**Comment by bwoodsend** [comment]
I've gone ahead and hit the release button in the hopes that I won't be receiving a new duplicate of this bug report each day for the next two weeks.
```bash
pip install "pyinstaller-hooks-contrib>=2022.15"
```

**Comment by bwilso1** [comment]
i'm running PyInstaller==5.10.1, and I still have to use this work around `--hiddenimport charset_normalizer.md__mypyc`

mentioned here.
https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/534#issuecomment-1382115687

If this was reported against 5.7 and was "merged" how is this not currently fixed?

I can only show this at runtime after the .exe is built.
`  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md__mypyc'
[12748] Failed to execute script 'main' due to unhandled exception!`

and the above errors go away when i compile with --hiddenimports

**Comment by bwoodsend** [comment]
The fix is in the hooks repo so it's `pyinstaller-hooks-contrib` you need to upgrade.

**Comment by arossert** [comment]
Sorry, there is a new issue, I created a new PR
https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/994
