### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by EggRolllll** [pyinstaller/pyinstaller-hooks-contrib#554]
Traceback (most recent call last):
  File "IRaman_v2_Map.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pylablib\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pylablib\core\devio\__export__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pylablib\core\devio\comm_backend.py", line 280, in <module>
  File "pylablib\core\devio\comm_backend.py", line 302, in VisaDeviceBackend
  File "pylablib\core\utils\module.py", line 44, in cmp_versions
TypeError: '>' not supported between instances of 'str' and 'int'

Hello. I am developing Thorlabs stage control function using pylablib. It works fine in the code, but when I create an exe file using pyinstaller, the above error occurs.

**Comment by bwoodsend** [comment]
Can you provide a reproducer example please.

**Comment by EggRolllll** [comment]
> `pyvisa` requires its metadata to properly determine its version (even though it has it hardcoded in `pyvisa.version`); otherwise it is `"unknown"`, which raises error during comparison in `pylablib.core.devio.comm_backend`.
> 
> Add a `--copy-metadata pyvisa` to your PyInstaller command (or create an equivalent hook).

I solved the problem this way. Thank you very much
