### ISSUE TITLE
PyInstaller issue with `transformers\__init__.py` file not found

### ISSUE THREAD

**Issue by Abhishek-Varma** [pyinstaller/pyinstaller-hooks-contrib#562]
Not sure what's the right place for this issue that I'm facing.

I'm trying to use PyInstaller to make an executable for a python program.

Steps to reproduce the error mentioned in this thread :-
1: Fetch [myprog.py](https://gist.github.com/Abhishek-Varma/71ca5a5802570b8c293551d8cf6302d4).
2: Fetch the concerned [myprog_installer.spec](https://gist.github.com/Abhishek-Varma/71ca5a5802570b8c293551d8cf6302d4).
3: Download a [.safetensor file](https://huggingface.co/Linaqruf/anything-v3.0/resolve/main/anything-v3-fp16-pruned.safetensors).
4: Run `pyinstaller myprog_installer.spec`.
5: Run `.\myprog_cli.exe --checkpoint_path=/path/to/the/safetensors/file`.
     Eg: `.\myprog_cli.exe --checkpoint_path=C:\A\anything-v3-fp16-pruned.safetensors`
             
I am bumping into the following error :-
```
Traceback (most recent call last):
  File "transformers\utils\import_utils.py", line 1126, in _get_module
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "transformers\models\blip\processing_blip.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "transformers\processing_utils.py", line 30, in <module>
  File "transformers\utils\import_utils.py", line 1155, in direct_transformers_import
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\abhishek\\AppData\\Local\\Temp\\_MEI3061642\\transformers\\__init__.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "myprog.py", line 3, in <module>
    from diffusers.pipelines.stable_diffusion.convert_from_ckpt import (
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\__init__.py", line 55, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\__init__.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\alt_diffusion\__init__.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\alt_diffusion\pipeline_alt_diffusion.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\stable_diffusion\__init__.py", line 81, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_pix2pix_zero.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "transformers\utils\import_utils.py", line 1117, in __getattr__
  File "transformers\utils\import_utils.py", line 1116, in __getattr__
  File "transformers\utils\import_utils.py", line 1128, in _get_module
RuntimeError: Failed to import transformers.models.blip.processing_blip because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: 'C:\\Users\\abhishek\\AppData\\Local\\Temp\\_MEI3061642\\transformers\\__init__.py'
[294208] Failed to execute script 'myprog' due to unhandled exception!
```

As a workaround I tried commenting a few import lines from `diffusers` and even tried following a similar workaround mentioned in [scikit issue with PyInstaller](https://github.com/scikit-image/scikit-image/issues/6772#issuecomment-1449671566) but the main crux of the `transformers\__init__.py` error still remains :-

```
Traceback (most recent call last):
  File "transformers\utils\import_utils.py", line 1126, in _get_module
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "transformers\processing_utils.py", line 30, in <module>
  File "transformers\utils\import_utils.py", line 1155, in direct_transformers_import
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\abhishek\\AppData\\Local\\Temp\\_MEI3065682\\transformers\\__init__.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "myprog.py", line 40, in <module>
    get_stable_diffusion(args.checkpoint_path)
  File "myprog.py", line 27, in get_stable_diffusion
    pipe.save_pretrained(path_to_diffusers)
  File "diffusers\pipelines\pipeline_utils.py", line 492, in save_pretrained
  File "transformers\utils\import_utils.py", line 1116, in __getattr__
  File "transformers\utils\import_utils.py", line 1128, in _get_module
RuntimeError: Failed to import transformers.processing_utils because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: 'C:\\Users\\abhishek\\AppData\\Local\\Temp\\_MEI3065682\\transformers\\__init__.py'
[291000] Failed to execute script 'myprog' due to unhandled exception!
```

**Comment by rokm** [comment]
Looks like `transformers` is trying to import modules based on their source files, which are unavailable in the frozen application.

You will need to force collection of `transformers` in the source mode. E.g., create [a hook](https://pyinstaller.org/en/stable/hooks.html) for `transformers` that sets [`module_collection_mode` global hook variable](https://pyinstaller.org/en/stable/hooks.html#hook-global-variables) to either `'py'` or `'pyz+py'`.

**Comment by Abhishek-Varma** [comment]
Thanks @rokm your inputs helped me get around this issue! :D

For some reason I was unable to spin off a unit test while trying to contribute the hook back to the community.

**Comment by albert-dim** [comment]
I had exactly the same issue and was able to resolved by adding these lines in my script.py.

os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "true"
os.environ["TRANSFORMERS_NO_LAZY"] = "1"

**Comment by bwoodsend** [comment]
`pip install -U pyinstaller-hooks-contrib` then a rebuild with `--clean` didn't do the job?
