### ISSUE TITLE
hook-transformers fails to run due to partially initialized huggingface_hub

### ISSUE THREAD

**Issue by GeorgWa** [pyinstaller/pyinstaller-hooks-contrib#721]
**Describe the bug**
One of our pyinstaller workflow currently fails on the `transformers` and`huggingface_hub` packages as it can't import the `huggingface_hub` module during discovery.

We've observed this so far only in our GitHub actions CD workflow using the M1 runners. If we run the same .spec locally in a clean conda environment using a M3 MBP it works fine. Unfortunately, we are struggling to reproduce this behaviour locally.

Do you have any ideas where the issue is or recommendations how we can investigate this?

Environment
```
transformers-4.38.2
huggingface-hub-0.21.4
pyinstaller-6.5.0 pyinstaller-hooks-contrib-2024.3
```

Error:
```
93 INFO: PyInstaller: 6.5.0, contrib hooks: 2024.3
193 INFO: Python: 3.11.8 (conda)
205 INFO: Platform: macOS-13.6.6-arm64-arm-64bit
...
55524 INFO: Loading module hook 'hook-transformers.py' from '/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
55716 WARNING: hook-transformers: failed to query dependency table (transformers.dependency_versions_table.deps)!
Traceback (most recent call last):
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/PyInstaller/utils/hooks/__init__.py", line 282, in get_module_attribute
    return _get_module_attribute(module_name, attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/PyInstaller/isolated/_parent.py", line 420, in wrapped
    return call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/PyInstaller/isolated/_parent.py", line 389, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/PyInstaller/isolated/_parent.py", line 319, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to _get_module_attribute() failed with:
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/PyInstaller/isolated/_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/PyInstaller/utils/hooks/__init__.py", line 277, in _get_module_attribute
    module = importlib.import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/transformers/utils/__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/__init__.py", line 403, in <module>
    __getattr__, __dir__, __all__ = _attach(__name__, submodules=[], submod_attrs=_SUBMOD_ATTRS)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/__init__.py", line 398, in _attach
    __getattr__(attr)
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/__init__.py", line 379, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 50, in <module>
    from ._commit_api import (
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/_commit_api.py", line 17, in <module>
    from huggingface_hub import get_session
ImportError: cannot import name 'get_session' from partially initialized module 'huggingface_hub' (most likely due to a circular import) (/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/huggingface_hub/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-transformers.py", line 17, in <module>
    dependencies = get_module_attribute(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/miniconda3/envs/alpha/lib/python3.11/site-packages/PyInstaller/utils/hooks/__init__.py", line 284, in get_module_attribute
    raise AttributeError(f"Failed to retrieve attribute {attr_name} from module {module_name}") from e
AttributeError: Failed to retrieve attribute deps from module transformers.dependency_versions_table
```

**Comment by rokm** [comment]
Hmmm, we could make the error in hook non-fatal, but I suppose if `transformers` is not importable (due to `huggingface_hub` error), the modulegraph won't be able to analyze submodules, either, and you'll end up with defunct build anyway.

**Comment by rokm** [comment]
FWIW, I get similar error locally on linux if I define `EAGER_IMPORT=true` environment variable before trying to run python and import `huggingface_hub`. I take it you ran your local builds without defining the environment variable?

**Comment by GeorgWa** [comment]
I think the error is already non-fatal as the build will continue. It will be broken though due to missing data.

Very good point! I guess I missed this when running my builds locally which still worked fine. I will check it without `EAGER_IMPORT`.

**Comment by GeorgWa** [comment]
Can be closed as it was adressed in https://github.com/huggingface/huggingface_hub/pull/2211
