### ISSUE TITLE
2024.5 issue importing cryptography hook during build

### ISSUE THREAD

**Issue by alexlambson** [pyinstaller/pyinstaller-hooks-contrib#736]
**Describe the bug**

The issue gets raised while creating a build; the failing import is `from PyInstaller import isolated`

The failing hook is `cryptography`.

**To Reproduce**

I had a former working build that started breaking with the release of 2024.5. Rolling back to 2024.4 fixed the issue.
I may need some hand holding on finding the reproduction steps. My command is `pyinstaller --clean -y -n MyPackageName`

Error:

```
Loading module hook 'hook-cryptography.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.8.10\\x64\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\depend\imphook.py", line 408, in _load_hook_module
    self._hook_module = importlib_load_source(
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\compat.py", line 632, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1027, in load_module
  File "<frozen importlib._bootstrap_external>", line 852, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py", line 21, in <module>
    from PyInstaller import isolated
ImportError: cannot import name 'isolated' from 'PyInstaller' (C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\building\build_main.py", line 813, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\building\build_main.py", line 760, in build
    exec(code, spec_namespace)
  File "specfile", line 7, in <module>
    a = Analysis(['src\\windows_build\\executable.py'],
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\building\build_main.py", line 292, in __init__
    self.__postinit__()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\building\datastruct.py", line 159, in __postinit__
    self.assemble()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\building\build_main.py", line 471, in assemble
    self.graph.process_post_graph_hooks(self)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\depend\analysis.py", line 373, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\depend\imphook.py", line 451, in post_graph
    self._load_hook_module()
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\PyInstaller\depend\imphook.py", line 412, in _load_hook_module
    raise ImportErrorWhenRunningHook(
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_cryptography required by hook for module C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py. Please check whether module __PyInstaller_hooks_0_cryptography actually exists and whether the hook is compatible with your version of C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.
```

**Desktop (please complete the following information):**
 - OS: Windows GitHub runner
 - Python Version: 3.8.10
 - Version of `pyinstaller-hooks-contrib`: 2024.5
 - Version of PyInstaller: 4.5

**Comment by bwoodsend** [comment]
That's an ancient version of PyInstaller. You'll need PyInstaller >= 5.0 for that to work.

There's a wider problem here of minimum supported PyInstaller versions although I can't think of a good way of solving it.

**Comment by alexlambson** [comment]
Ah, if that's the case then I'll close this. Apologies

**Comment by jeremymartin-snowden** [comment]
I have just encountered the same issue using pyinstaller 4.5.1 and it's been stable for a long time. Does this suggest that internally the library does not lock down its internal dependencies?

**Comment by rokm** [comment]
In general, I would prefer if we officially dropped support for old PyInstaller versions in these hooks; that way, we could migrate them all to contemporary `isolated` framework, and other functionality from PyInstaller >= 5.0. For that to work, we would have to yank 2024.5, and release 2024.6 with enforced "PyInstaller >= 5.0" requirement.

But in this particular case, I think we could add a "PyInstaller >= 5.0" check to the hook, and disable the part that requires `isolated`. We use that to identify OpenSSL >= 3.0, but then we require "PyInstaller >= 6.0" anyway to find the shared lib and collect the modules. So I think putting everything under "PyInstaller >= 6.0" check would make sense. Or maybe even an old `exec_statement` fallback for OpenSSL identification, so that we display warning about requiring PyInstaller >= 6.0 only if OpenSSL >= 3.0.

**Comment by bwoodsend** [comment]
Out of curiosity, why are you aggressively keeping your `pyinstaller-hooks-contrib` version up to date but letting `pyinstaller` rot on a version two and a half years old?

**Comment by alexlambson** [comment]
Pyinstaller's dependency says `>` so it has been keeping contrib up to date on its own.

**Comment by bwoodsend** [comment]
> It's similar to pinning PyQt6 but not PyQt6-Qt6, until one day it breaks and you become aware that it exists...

Ahh, that makes sense. But I really don't like the implication that we're expected to keep guards and workarounds for every single PyInstaller feature that has been added since v4.0. Letting people sit on unsupported (and in this case CVE carrying) PyInstaller versions feels like a poor justification for that constraint.

We *could* add an arbitrary upper bound [here](https://github.com/pyinstaller/pyinstaller/blob/ba3ccc68be8dff67106e39d85873ca8165b9677f/setup.cfg#L68) of say a year above the lower bound which would mean that this repo can assume that it'll never encounter a PyInstaller installation more than a year out of date? I'd be pretty reluctant to do that too though. Upper bounds invariably break more environments than they save in my experience.

Perhaps the easiest solution would be just to put *if you choose to pin pyinstaller, you should also pin pyinstaller-hooks-contrib* in the installation page of the documentation?

**Comment by rokm** [comment]
Would it be unfeasible to put the "PyInstaller >= 5.0" requirement to the pyinstaller-hooks-contrib, though (i.e., does it create a cyclic dependency that pip cannot handle)? I would imagine that would leave users of old PyInstaller versions with the last version that did not have the requirement, and we can carry on with using new functionality in the subsequent releases?

**Comment by bwoodsend** [comment]
> Would it be unfeasible to put the "PyInstaller >= 5.0" requirement to the pyinstaller-hooks-contrib, though (i.e., does it create a cyclic dependency that pip cannot handle)?

Pip can't see if a version of `pyinstaller-hooks-contrib` supports a version of `pyinstaller` without downloading it first (or with newer pips, its corresponding `.whl.metadata` file) so it has to brute force search its way down from the latest version of `pyinstaller-hooks-contrib`, downloading a wheel or metadata file for each version, until if finds a compatible pairing. Other than that though, it works pretty well.

I think this will be more disruptive though for the downstream packagers (e.g. brew) that we haven't managed to dissuade from repackaging PyInstaller.

**Comment by bwoodsend** [comment]
Well whatever. My mind's pretty set on the *a sentence in the docs* plan...

**Comment by alexlambson** [comment]
Upgrading to PyInstaller 6.6 fixed the issue, in case anyone arrives from google.

**Comment by rokm** [comment]
> Well whatever. My mind's pretty set on the _a sentence in the docs_ plan...

OK, let's do it that way, then.
