### ISSUE TITLE
Trying to import "isolated" from "PyInstaller" when pyinstaller version is lower than 5

### ISSUE THREAD

**Issue by wallace-pinho** [pyinstaller/pyinstaller-hooks-contrib#741]
**Describe the bug**
* Which hook/library isn't working? cryptography
* Does the error get raised while building or when running? While building

**To Reproduce**
1. Create a new python project 
2. Create and activate a virtual environment using venv
3. Install PyInstaller 4.10
4. Build the project using the command below

A minimal example file:
Irrelevant to reproduce the error.

PyInstaller command:
```
pyinstaller --onefile -p .\src --name ProjectName src\__main__.py
```
In this case, using `-p` specifically made the error occur

Error:
```
8738 INFO: Loading module hook 'hook-cryptography.py' from 'C:\\ProjectName\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
Traceback (most recent call last):
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 361, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\compat.py", line 641, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProjectName\venv\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py", line 21, in <module>
    from PyInstaller import isolated
ImportError: cannot import name 'isolated' from 'PyInstaller' (C:\ProjectName\venv\lib\site-packages\PyInstaller\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProjectName\venv\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\building\build_main.py", line 803, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\building\build_main.py", line 725, in build
    exec(code, spec_namespace)
  File "C:\ProjectName\ProjectName.spec", line 7, in <module>
    a = Analysis(['src\\__main__.py'],
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\building\build_main.py", line 277, in __init__
    self.__postinit__()
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\building\build_main.py", line 445, in assemble
    self.graph.process_post_graph_hooks(self)
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 326, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 398, in post_graph
    self._load_hook_module()
  File "C:\ProjectName\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 364, in _load_hook_module
    raise ImportErrorWhenRunningHook(self.hook_module_name, self.hook_filename)
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_cryptography required by hook for module C:\ProjectName\venv\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py. Please check whether module __PyInstaller_hooks_0_cryptography actually exists and whether the hook is compatible with your version of C:\ProjectName\venv\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.
```

**Expected behavior**
The project should build

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.10
 - Version of `pyinstaller-hooks-contrib`: 2024.5
 - Version of PyInstaller 4.10

**Additional context**
While investigating the issue, it seem the following commit made the error occur: https://github.com/pyinstaller/pyinstaller-hooks-contrib/commit/0aa223a311be4e10c9c71426d6c8877c48776ca2#diff-5af64aa9e9a27bdc6cd30b8ff77c99b35836aa6921329376aa2578344dced562L20
`isolated` seems to be available from `PyInstaller` only on version >=5 of PyInstaller. It is though available in `PyInstaller.utils.hooks` in version 4.10.

**Comment by rokm** [comment]
PyInstaller 4.x is not supported anymore - if you have to use it for whatever reason, you should pin `pyinstaller-hooks-contrib` in addition to `PyInstaller`. See https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/736
