### ISSUE TITLE
pysintaller with scipy

### ISSUE THREAD

**Issue by happymvd** [pyinstaller/pyinstaller-hooks-contrib#755]
I am trying to compile my python code that includes the scipy library which is imported in my code as follows - 
**from scipy.spatial import ConvexHull**

The code compiles, but when I try and execute the exe I get the following message - 
Traceback (most recent call last):
  File "Datum.py", line 37, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "SWF.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\spatial\__init__.py", line 110, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\spatial\_kdtree.py", line 4, in <module>
  File "_ckdtree.pyx", line 11, in init scipy.spatial._ckdtree
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\sparse\__init__.py", line 293, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\sparse\_base.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\sparse\_sputils.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\_lib\_util.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\_lib\_array_api.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\_lib\array_api_compat\numpy\__init__.py", line 18, in <module>
ModuleNotFoundError: No module named 'scipy._lib.array_api_compat.numpy.fft'

Please can someone suggest a possible solution for me

**Comment by rokm** [comment]
Downgrade scipy to 1.13.1. Or add `scipy._lib.array_api_compat.numpy.fft` to hidden imports. See https://github.com/pyinstaller/pyinstaller/pull/8622

**Comment by happymvd** [comment]
Thank you - 
I have a folder called "extra-hooks" with a file "hook-array.py" (that you have suggested to me before)
The contents of the file file are - 
# hook-xarray.py
from PyInstaller.utils.hooks import copy_metadata, collect_entry_point

# Collect additional backend plugins
datas, hiddenimports = collect_entry_point('xarray.backends')

# `xarray` requires `numpy` metadata due to several calls to its `xarray.core.utils.module_available` with specified
# `minversion` argument, which end up calling `importlib.metadata.version`.
datas += copy_metadata('numpy')

I know nothing about these things ..... how will I add "scipy._lib.array_api_compat.numpy.fft" to the hidden imports?

**Comment by rokm** [comment]
> I know nothing about these things ..... how will I add "scipy._lib.array_api_compat.numpy.fft" to the hidden imports?

If you are building directly from .py file, add [`--hiddenimport scipy._lib.array_api_compat.numpy.fft`](https://pyinstaller.org/en/stable/usage.html#cmdoption-hidden-import) to your PyInstaller command. If you are building from spec, append the module's name to the list that is passed to `hiddenimports` argument in `Analysis` constructor. You could also append it to the `hiddenimports` list in that `xarray` hooks, but it is best not to mix hooks and unrelated packages.

**Comment by happymvd** [comment]
Thank you very much .....
I went back to version 1.13.1 as you suggested, and I got the same message when I tried to execute the exe file.
I will add the hidden import command when I compile
Very much appreciated ......

**Comment by happymvd** [comment]
I still get the following message - 
Traceback (most recent call last):
  File "Datum.py", line 37, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "SWF.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\spatial\__init__.py", line 110, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\spatial\_kdtree.py", line 4, in <module>
  File "_ckdtree.pyx", line 11, in init scipy.spatial._ckdtree
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\sparse\__init__.py", line 293, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\sparse\_base.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\sparse\_sputils.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\_lib\_util.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\_lib\_array_api.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\_lib\array_api_compat\numpy\__init__.py", line 18, in <module>
ModuleNotFoundError: No module named 'scipy._lib.array_api_compat.numpy.fft'

I used this command to compile - 
pyinstaller --onefile --noconsole --additional-hooks-dir extra-hooks  --hiddenimport scipy._lib.array_api_compat.numpy.fft SearchWell.py --collect-data gribapi

Sorry to be a pain

**Comment by rokm** [comment]
Scipy 1.13.1 doesn't have `scipy._lib.array_api_compat.numpy.fft` at all, as that was introduced with 1.14.0 - so if you're seeing that error, then either you downgraded scipy in the wrong python environment (i.e., not the one you are running pyinstaller from). Or maybe there's an issue with caching - try to add `--clean` option to your PyInstaller command to force a clean build.

Also, is that complete exception traceback? I find it a bit odd that `Datum.py` is the first entry, whereas your entry-point script is called `SearchWell.py`...

**Comment by happymvd** [comment]
OK, and again, a huge thank you - 
I went back to version 1.13.1 and I got the message that there was no module "scipy.special._cdflib.
So I added "--hiddenimport scipy.special._cdflib" to the compile command ..... and it worked.
I will just document that we must not upgrade scipy

**Comment by rokm** [comment]
>  I went back to version 1.13.1 and I got the message that there was no module "scipy.special._cdflib.

This was fixed in PyInstaller v6.6.0.

**Comment by happymvd** [comment]
Ahhhh, then I will upgrade PyInstaller ..... 
Your knowledge and patience is much appreciated
