### ISSUE TITLE
hook-cryptography 2024.7 is incompatible with pyinstaller 4.5.1

### ISSUE THREAD

**Issue by dtyeos** [pyinstaller/pyinstaller-hooks-contrib#758]
**Describe the bug**
*hook-cryptography* requires ``PyInstaller.isolated`` which looks like to have been included in *PyInstaller 5.0*.
But *PyInstaller 4.5.1* is the most recent version compatible with *Python 3.9.13* (which I cannot upgrade yet).

**To Reproduce**
I would be glad to provide you with a minimal setup to reproduce but the conditions making PyInstaller enabling this specific hook are really obscure to me.

Error:
```
96355 PyInstaller.depend.imphook: Loading module hook 'hook-cryptography.py' from 'C:\\Users\\dtylski\\.virtualenvs\\EOSNG-TwinCAT-Scripts-2tvUVafm\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
Traceback (most recent call last):
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\depend\imphook.py", line 408, in _load_hook_module
    self._hook_module = importlib_load_source(
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\compat.py", line 632, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py", line 21, in <module>
    from PyInstaller import isolated
ImportError: cannot import name 'isolated' from 'PyInstaller' (C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\EOS4.x\EOSNG-TwinCAT-Scripts\src\build.py", line 354, in make_all_executables
    logger.info("----- Build of %s: end", name)
  File "C:\EOS4.x\EOSNG-TwinCAT-Scripts\src\build.py", line 337, in make_executable

  File "C:\EOS4.x\EOSNG-TwinCAT-Scripts\src\build.py", line 320, in run_pyinstaller

  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\building\build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\building\build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "C:\EOS4.x\EOSNG-TwinCAT-Scripts\spec\setup_cfast-2.1.0.exe.spec", line 7, in <module>
    a = Analysis(['C:\\EOS4.x\\EOSNG-TwinCAT-Scripts\\src\\setup_cfast\\__main__.py'],
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\building\build_main.py", line 294, in __init__
    self.__postinit__()
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\building\datastruct.py", line 159, in __postinit__
    self.assemble()
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\building\build_main.py", line 473, in assemble
    self.graph.process_post_graph_hooks(self)
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\depend\analysis.py", line 373, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\depend\imphook.py", line 451, in post_graph
    self._load_hook_module()
  File "C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\PyInstaller\depend\imphook.py", line 412, in _load_hook_module
    raise ImportErrorWhenRunningHook(
PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_6_cryptography required by hook for module C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py. Please check whether module __PyInstaller_hooks_6_cryptography actually exists and whether the hook is compatible with your version of C:\Users\dtylski\.virtualenvs\EOSNG-TwinCAT-Scripts-2tvUVafm\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-cryptography.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.9.13
 - Version of `pyinstaller-hooks-contrib`: 2024.7
 - Version of PyInstaller: 4.5.1

**Additional context**
The issue disappears when forcing the use of *pyinstaller-hooks-contrib 2024.2* with *PyInstaller 4.5.1*.

This is some version dependency issue between pyinstaller and this set of hooks: maybe the issue should instead be reported to pyinstaller? I don't know where and how the Python module dependencies are managed, but I will probably learn something from that issue :)

**Comment by rokm** [comment]
PyInstaller 4.x is not supported anymore - if you have to use it for whatever reason, you should pin `pyinstaller-hooks-contrib` in addition to `PyInstaller`. See https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/736
